name: Auto Deploy
on:
  push:
    branches: [ "main" ]
env:
  CI: false
  REACT_APP_GOAP: ${{ secrets.REACT_APP_GOAP }}
  REACT_APP_SV: ${{ secrets.REACT_APP_SV }}
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.20.0]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: git config --global user.email "juanpabloazambuyo@gmail.com"
    - run: git config --global user.name "Juan Pablo Azambuyo"
    - run: git remote set-url origin https://${{secrets.USER_GITHUB_TOKEN}}@github.com/PabloAza89/PI-Food-GH.git
    - run: npm run deploy --if-present